# Generated by Django 4.2 on 2024-05-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('REPORT', 'REPORT')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
