version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0:80"
    restart: always
    container_name: develop-env

  celery_worker:
    build: .
    volumes:
      - .:/app
    command: celery -A OpinionProject worker -l info
    restart: always
    container_name: celery-worker
    depends_on:
      - web

  celery_beat:
    build: .
    volumes:
      - .:/app
    command: celery -A OpinionProject beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    container_name: celery-beat
    depends_on:
      - web