# Generated by Django 4.2 on 2024-05-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='hello', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
