# Generated by Django 4.2 on 2024-05-20 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onions', '0002_rename_user_onion_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='onion',
            name='parent_onion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_onions', to='onions.onion'),
        ),
    ]
