# Generated by Django 4.2 on 2024-05-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onions', '0003_onion_parent_onion'),
    ]

    operations = [
        migrations.AddField(
            model_name='onion',
            name='color',
            field=models.CharField(choices=[('Orange', 'Orange'), ('Purple', 'Purple')], default='Purple', max_length=10),
            preserve_default=False,
        ),
    ]
