# Generated by Django 4.2 on 2024-05-23 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onions', '0004_onion_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='onionversus',
            name='orange_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='onionversus',
            name='purple_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='onionversus',
            name='title_embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='onion',
            name='num_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
