# Generated by Django 4.2 on 2024-05-26 12:33

from pgvector.django import VectorExtension
from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('onions', '0006_onionversus_ov_title'),
    ]

    operations = [
        VectorExtension(),
        migrations.AlterField(
            model_name='onionversus',
            name='orange_embedding',
            field=pgvector.django.VectorField(dimensions=768),
        ),
        migrations.AlterField(
            model_name='onionversus',
            name='purple_embedding',
            field=pgvector.django.VectorField(dimensions=768),
        ),
        migrations.AlterField(
            model_name='onionversus',
            name='title_embedding',
            field=pgvector.django.VectorField(dimensions=768),
        ),
    ]
