# Generated by Django 4.2 on 2024-05-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pie',
            old_name='user',
            new_name='writer',
        ),
    ]
